version: "3.8"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./volumes/zookeeper-data:/var/lib/zookeeper/data
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - ./volumes/kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  dwh_postgres:
    image: postgres:15-alpine
    container_name: dwh-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/dwh_example:/var/lib/postgresql/data
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d chat_db"]
      interval: 10s
      timeout: 10s
      retries: 10
  
  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    restart: always
    depends_on:
      - dwh_postgres
    environment:
      NC_DB: "pg://dwh_postgres:5432?u=user&p=password&d=chat_db"
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/nocodb-data:/usr/app/data
      

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    container_name: chat-api
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8000:8000"

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    container_name: chat-consumer
    restart: always
    depends_on:
      dwh_postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DATABASE_URL: postgresql://user:password@dwh_postgres:5432/chat_db

  prefect-server:
    image: prefecthq/prefect:3-latest
    container_name: prefect-server
    restart: always
    command: prefect server start --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
    volumes:
      - ./volumes/prefect:/root/.prefect
    
  prefect-worker:
    image: prefecthq/prefect:3-python3.11
    container_name: prefect-worker
    restart: always
    volumes:
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "pip install --no-cache-dir -r /requirements.txt && 
      prefect worker start --pool 'default-agent-pool' --type process"
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PYTHONPATH=/opt/prefect/deployment_prefect
    depends_on:
      - prefect-server